services:
  postgres-db:
    container_name: neon_ark_capstone_db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: neonark
      POSTGRES_PASSWORD: neonarkpass
      POSTGRES_DB: neon_ark_capstone
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5438:5432"
    volumes:
      - neonark_capstone_pgdata:/var/lib/postgresql/data

volumes:
  neonark_capstone_pgdata:
    driver: local
