CREATE TABLE habitats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    zone VARCHAR(120),
    capacity INT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_habitats_capacity CHECK (capacity >= 0)
);

CREATE TABLE creatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    species VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    habitat_id BIGINT NOT NULL,
    removed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_creatures_habitats FOREIGN KEY (habitat_id) REFERENCES habitats(id),
    CONSTRAINT uq_creatures_habitat_name UNIQUE (habitat_id, name),
    CONSTRAINT chk_creatures_status CHECK (status IN ('ACTIVE', 'INTAKE', 'REMOVED')),
    CONSTRAINT chk_creatures_removed_at CHECK (
        (status = 'REMOVED' AND removed_at IS NOT NULL)
        OR (status <> 'REMOVED' AND removed_at IS NULL)
    )
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_users FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creature_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    note TEXT NOT NULL,
    observed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_observations_creatures FOREIGN KEY (creature_id) REFERENCES creatures(id),
    CONSTRAINT fk_observations_users FOREIGN KEY (author_id) REFERENCES app_users(id),
    CONSTRAINT chk_observations_note CHECK (length(trim(note)) > 0)
);

CREATE TABLE feeding_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creature_id BIGINT NOT NULL,
    feeding_time TIME WITHOUT TIME ZONE NOT NULL,
    food VARCHAR(120) NOT NULL,
    instructions VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feeding_schedules_creatures FOREIGN KEY (creature_id) REFERENCES creatures(id),
    CONSTRAINT uq_feeding_creature_time UNIQUE (creature_id, feeding_time),
    CONSTRAINT chk_feeding_food CHECK (length(trim(food)) > 0)
);

CREATE INDEX idx_creatures_status ON creatures(status);
CREATE INDEX idx_observations_creature ON observations(creature_id);
CREATE INDEX idx_feeding_time_active ON feeding_schedules(feeding_time, active);

